#pragma once

#include <Engine/Graphics/CommandBuffer.h>
#include <Engine/GUI/Renderer/RenderBatch.h>

#include <algorithm>
#include <limits>

namespace Elixir::GUI
{
    constexpr size_t GrowBufferCapacity(const size_t capacity, const size_t requiredCapacity)
    {
        if (requiredCapacity <= capacity)
            return capacity;

        if (capacity > std::numeric_limits<size_t>::max() / 2)
            return requiredCapacity;

        return std::max(requiredCapacity, capacity * 2);
    }

    class RenderPass
    {
    public:
        virtual ~RenderPass() = default;

        /**
         * @brief Discards the geometry accumulated last frame.
         * Called once per frame, on every registered pass, before any AppendRange call.
         */
        virtual void BeginFrame() = 0;

        /**
         * @brief Uploads the geometry accumulated across this frame's AppendRange calls
         * to the GPU in a single call.
         *
         * Called once per frame, on every registered pass, after the last AppendRange.
         */
        virtual void EndFrame() = 0;

        /**
         * @brief Builds GPU geometry for one contiguous same-type run and appends it to
         * this pass's per-frame instance buffer.
         *
         * @param commands Span over a single SBatchRun's slice of RenderBatch::GetCommands().
         * @return Index of the first instance generated by this call.
         *
         * @note The number of instances appended is not necessarily commands.size() - e.g.
         * TextRenderPass expands each command into one instance per glyph. Read the actual
         * count produced via GetInstanceCount() right after this call.
         */
        virtual uint32_t AppendRange(std::span<const SDrawCommand> commands) = 0;

        /**
         * @brief Binds this pass's pipeline and vertex buffer.
         *
         * The Renderer calls this only when the pass differs from the one used by the
         * previous draw item.
         *
         * @param cmd The command buffer to record the bind commands into.
         */
        virtual void Bind(const Ref<CommandBuffer>& cmd) = 0;

        /**
         * @brief Issues the draw call for the [firstInstance, firstInstance + instanceCount)
         * range produced by an earlier AppendRange this frame.
         *
         * @param cmd The command buffer to record the draw commands into.
         * @param firstInstance The index of the first instance to draw.
         * @param instanceCount The number of instances to draw.
         */
        virtual void Render(
            const Ref<CommandBuffer>& cmd,
            uint32_t firstInstance,
            uint32_t instanceCount
        ) = 0;

        virtual bool HasData() const = 0;
        virtual void Clear() = 0;

        /**
         * @brief Total instances accumulated so far this frame.
         *
         * For passes that don't draw instanced, it handles
         * vertices count - see DebugRenderPass.
         *
         * @return The number of instances accumulated in this pass for this frame.
         */
        virtual uint32_t GetInstanceCount() const = 0;

        /**
         * The EDrawCommandType this pass consumes. The Renderer uses this at
         * registration time to route each SBatchRun to the pass responsible for it.
         * @return The type of draw commands this pass is responsible for rendering.
         */
        virtual EDrawCommandType GetHandleType() const = 0;
    };
}
